[versions]
guava = "33.3.1-jre"
junit = "4.13.2"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
